// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RulesDatabase;

namespace RulesDatabase.Migrations
{
    [DbContext(typeof(RulesDbContext))]
    [Migration("20210712133537_ImportedRules")]
    partial class ImportedRules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImportedRuleKeyword", b =>
                {
                    b.Property<int>("KeywordsId")
                        .HasColumnType("int");

                    b.Property<int>("RulesId")
                        .HasColumnType("int");

                    b.HasKey("KeywordsId", "RulesId");

                    b.HasIndex("RulesId");

                    b.ToTable("ImportedRuleKeyword");
                });

            modelBuilder.Entity("ImportedRuleSource", b =>
                {
                    b.Property<int>("RulesId")
                        .HasColumnType("int");

                    b.Property<int>("SourcesId")
                        .HasColumnType("int");

                    b.HasKey("RulesId", "SourcesId");

                    b.HasIndex("SourcesId");

                    b.ToTable("ImportedRuleSource");
                });

            modelBuilder.Entity("RulesDatabase.ImportedRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EncounterUses")
                        .HasColumnType("int");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PowerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerUsage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prereqs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WizardsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("WizardsId")
                        .IsUnique()
                        .HasFilter("[WizardsId] IS NOT NULL");

                    b.HasIndex("Type", "Name")
                        .IsUnique()
                        .HasFilter("[Type] IS NOT NULL AND [Name] IS NOT NULL");

                    b.ToTable("ImportedRules");
                });

            modelBuilder.Entity("RulesDatabase.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KeywordName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KeywordName")
                        .IsUnique()
                        .HasFilter("[KeywordName] IS NOT NULL");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("RulesDatabase.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SourceName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SourceName")
                        .IsUnique()
                        .HasFilter("[SourceName] IS NOT NULL");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("ImportedRuleKeyword", b =>
                {
                    b.HasOne("RulesDatabase.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RulesDatabase.ImportedRule", null)
                        .WithMany()
                        .HasForeignKey("RulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImportedRuleSource", b =>
                {
                    b.HasOne("RulesDatabase.ImportedRule", null)
                        .WithMany()
                        .HasForeignKey("RulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RulesDatabase.Source", null)
                        .WithMany()
                        .HasForeignKey("SourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RulesDatabase.ImportedRule", b =>
                {
                    b.OwnsMany("RulesDatabase.LinkedId", "AssociatedFeats", b1 =>
                        {
                            b1.Property<int>("ImportedRuleId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("WizardsId")
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("ImportedRuleId", "Id");

                            b1.HasIndex("WizardsId");

                            b1.ToTable("ImportedRules_AssociatedFeats");

                            b1.WithOwner()
                                .HasForeignKey("ImportedRuleId");
                        });

                    b.OwnsOne("RulesDatabase.LinkedId", "Class", b1 =>
                        {
                            b1.Property<int>("ImportedRuleId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("WizardsId")
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("ImportedRuleId");

                            b1.HasIndex("WizardsId");

                            b1.ToTable("ImportedRules");

                            b1.WithOwner()
                                .HasForeignKey("ImportedRuleId");
                        });

                    b.OwnsOne("RulesDatabase.LinkedId", "SkillPower", b1 =>
                        {
                            b1.Property<int>("ImportedRuleId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("WizardsId")
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("ImportedRuleId");

                            b1.HasIndex("WizardsId");

                            b1.ToTable("ImportedRules");

                            b1.WithOwner()
                                .HasForeignKey("ImportedRuleId");
                        });

                    b.OwnsMany("RulesDatabase.RulesTextEntry", "RulesText", b1 =>
                        {
                            b1.Property<int>("RuleId")
                                .HasColumnType("int");

                            b1.Property<int>("Order")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Label")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Text")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RuleId", "Order");

                            b1.ToTable("RulesTextEntry");

                            b1.WithOwner("Rule")
                                .HasForeignKey("RuleId");

                            b1.Navigation("Rule");
                        });

                    b.Navigation("AssociatedFeats");

                    b.Navigation("Class");

                    b.Navigation("RulesText");

                    b.Navigation("SkillPower");
                });
#pragma warning restore 612, 618
        }
    }
}
